data = [{"name": "Taylor Swift", "follower_count": 282, "occupation": "Singer-Songwriter", "country": "United States"},
        {"name": "Selena Gomez", "follower_count": 420, "occupation": "Singer and Actress", "country": "United States"},
        {"name": "Dwayne Johnson", "follower_count": 395, "occupation": "Actor and Wrestler", "country": "United States"},
        {"name": "Ariana Grande", "follower_count": 375, "occupation": "Singer", "country": "United States"},
        {"name": "Kim Kardashian", "follower_count": 365, "occupation": "Media Personality", "country": "United States"},
        {"name": "Beyoncé", "follower_count": 320, "occupation": "Singer", "country": "United States"},
        {"name": "Justin Bieber", "follower_count": 295, "occupation": "Singer", "country": "Canada"},
        {"name": "Kylie Jenner", "follower_count": 400, "occupation": "Media Personality", "country": "United States"},
        {"name": "Zendaya", "follower_count": 185, "occupation": "Actress", "country": "United States"},
        {"name": "Chris Hemsworth", "follower_count": 60, "occupation": "Actor", "country": "Australia"},
        {"name": "Tom Holland", "follower_count": 65, "occupation": "Actor", "country": "United Kingdom"},
        {"name": "Shah Rukh Khan", "follower_count": 48, "occupation": "Actor", "country": "India"},
        {"name": "Deepika Padukone", "follower_count": 80, "occupation": "Actress", "country": "India"},
        {"name": "Virat Kohli", "follower_count": 275, "occupation": "Cricketer", "country": "India"},
        {"name": "Priyanka Chopra", "follower_count": 92, "occupation": "Actress", "country": "India"},
        {"name": "Billie Eilish", "follower_count": 125, "occupation": "Singer", "country": "United States"},
        {"name": "Drake", "follower_count": 145, "occupation": "Rapper", "country": "Canada"},
        {"name": "Jennifer Lopez", "follower_count": 250, "occupation": "Singer and Actress", "country": "United States"},
        {"name": "Rihanna", "follower_count": 150, "occupation": "Singer", "country": "Barbados"},
        {"name": "Ed Sheeran", "follower_count": 50, "occupation": "Singer", "country": "United Kingdom"},
        {"name": "Emma Watson", "follower_count": 75, "occupation": "Actress", "country": "United Kingdom"},
        {"name": "Robert Downey Jr.", "follower_count": 58, "occupation": "Actor", "country": "United States"},
        {"name": "Ryan Reynolds", "follower_count": 55, "occupation": "Actor", "country": "Canada"},
        {"name": "Margot Robbie", "follower_count": 32, "occupation": "Actress", "country": "Australia"},
        {"name": "Keanu Reeves", "follower_count": 22, "occupation": "Actor", "country": "Canada"},
        {"name": "Jungkook", "follower_count": 78, "occupation": "Singer", "country": "South Korea"},
        {"name": "Lisa", "follower_count": 106, "occupation": "Singer", "country": "Thailand"},
        {"name": "Jennie", "follower_count": 88, "occupation": "Singer", "country": "South Korea"},
        {"name": "Pedro Pascal", "follower_count": 12, "occupation": "Actor", "country": "Chile"},
        {"name": "Sydney Sweeney", "follower_count": 25, "occupation": "Actress", "country": "United States"}]

